### ISSUE TITLE
CF featureType attribute check should be case-insensitive

### ISSUE THREAD

**Issue by mhidas** [ioos/compliance-checker#484] opened 2017-04-13 02:22 UTC
According to CF ([9.4](http://cfconventions.org/cf-conventions/v1.6.0/cf-conventions.html#featureType)) the value of the `featureType` global attribute is case-insensitive. This was allowed for in version 2.3, but in 3.0 it is not. So e.g. `featureType = "timeseries"` is no longer allowed, but it should be.

**Comment by lukecampbell** [comment] 2017-04-13 12:32
This is a duplicate of #461

**Closed** 2017-04-13 12:33 UTC
