### ISSUE TITLE
3.5 Flags and flag attributes - flag_values attr does not have same type as var

### ISSUE THREAD

**Issue by daf** [ioos/compliance-checker#192] opened 2015-11-11 18:02 UTC
Ran the new compliance-checker-web on the file referenced in #171 and got a number of "Corrective Actions" with the following text:

```
3.5 Flags and flag attributes	3	flag_values attr does not have same type as var (fv: int8, v: int16)
```

This is partially useful as it tells me what types were wrong (cryptically, though), but it does not tell me what variable.  Especially as there's a ton of these messages, all the same.

**Comment by daf** [comment] 2015-11-11 18:03
Actually, this may be an issue with compliance-checker-web's output formatting, @lukecampbell ?

**Comment by mhidas** [comment] 2015-11-12 07:15
@daf I've come across this as well and thought it should be fixed. I think it's a result of the new naming system for CF checks. For a lot of them the variable name (and sometimes useful - IMHO - third-level check names) were removed, leading to many check results being combined into one. Some other checks have the same issue:
 * 2.4 Dimension order
 * 3.1 Variables contain valid CF Units
 * 3.3 Standard Names

Sure, sometimes the variable name is included in the reasoning message, but that's not very easy to read when there's a whole bunch of them with the same error. e.g.
```
3.1 Variables contain valid CF Units   :3:     0/ 6 : unknown units type
                                                      (Degrees clockwise from
                                                      true North) for CDIR,
                                                      unknown units type
                                                      (Decibels) for ABSI1,
                                                      unknown units type
                                                      (Decibels) for ABSI2,
                                                      unknown units type
                                                      (Decibels) for ABSI3,
                                                      ... etc ...
```

**Comment by DanielJMaher** [comment] 2016-02-15 19:08
"Someone needs to revisit the 3.5 test and make sure the variable is being passed " - Luke

**Comment by benjwadams** [comment] 2016-03-14 17:23
I can generate this myself, but it'd be preferable to attach an .nc file or minimal example to reproduce.

**Comment by benjwadams** [comment] 2016-03-14 17:30
@daf file referenced in link is currently 404.  Can make a minimal example to reproduce but would prefer using the original file to reproduce.

**Comment by benjwadams** [comment] 2016-03-14 18:55
Never mind, there's an example contained within the test data that accomplishes something similar.

**Closed** 2016-03-14 19:04 UTC
Labels: Checker Issue
