### ISSUE TITLE
Unidentifiable feature type for timeseries

### ISSUE THREAD

**Issue by lukecampbell** [ioos/compliance-checker#446] opened 2016-11-16 12:54 UTC
[test_201610.nc.zip](https://github.com/ioos/compliance-checker/files/594672/test_201610.nc.zip)

`air_temperature` is an unidentifiable feature type, but it should be detectable and labeled as time-series.

**Comment by benjwadams** [comment] 2019-02-13 16:12
I am unable to reproduce this using the file supplied with either the current CF or ACDD checkers, so I'm going to close this issue.

**Closed by benjwadams** 2019-02-13 16:12 UTC
