### ISSUE TITLE
CF module: misleading and erroneous results

### ISSUE THREAD

**Issue by martinjuckes** [ioos/compliance-checker#501] opened 2017-07-19 12:20 UTC
I've been looking at the IOOS compliance checker cf module, and comparing against the cfchecker (available from pypi) which is a reference implementation. The comparison, using files with known errors, turned up one problem with the cfchecker (which I've raised on their discussion list) and a number of issues with the IOOS implementation listed below. 

The original files I used are from the WCRP CMIP5 archive ... available to registered users. In order to make the discussion easier I've created some anonymised and reduced (by spatial and temporal subsetting) files which have the same metadata errors: 

[https://drive.google.com/open?id=0B6AWgiTrQ0xFMHBEUVNXYzc3YUE](sos_Omon_exAA03_historical_r3i1p1_185001-200512_box.nc)
(1) The IOOS checker records use of Conventions=CF-1.4 as an error: this was the current version of the conventions at the time the file was written, so should not be considered as an error. Rather, it is an indication that the compliance checker should check the metadata against version 1.4 of the standard.

[https://drive.google.com/open?id=0B6AWgiTrQ0xFQ1J0bFVDNlpyV1k](tnhus_cfSites_exAA04_amip_r3i1p1_1998_slice.nc)
(2) The variable “aps” is referred to in a formula_terms attribute but not defined: IOOS misses this;
(3) IOOS is distributed with an old version of the CF standard name table which results in spurious errors … this could probably be fixed by switching the file .. but there is no obvious warning.
(4) IOOS records the omission of both a standard name and long name for a variable as an error, the CF standard states that use of at least one of these as “highly recommended” (the IOOS error message give the wrong section for this: 3.3 instead of 3.2)

[https://drive.google.com/open?id=0B6AWgiTrQ0xFX2hQMW9VTUtCQ1k](zsatcalc_Omon_exAA07_abrupt4xCO2_r1i1p1_013601-014012_box.nc) 
(5) Cf-checker lists one error in the cell_methods string, IOOS has this as a priority 2 message -- which is usually associated with a warning.
(6) The IOOS checker has a message that “latitude variable 'rlat' should define valid units for latitude” which is incorrect: the ‘rlat’ variable has standard name grid_latitude, and the definition of grid_latitude specifies that “degree”, as used in the above file, is correct.

[https://drive.google.com/open?id=0B6AWgiTrQ0xFbXhXTlgzS0MwU3M](hurs_Amon_exAA05_decadal1981_r1i1p1_198201-199112_box.nc) 
(7) There is an error in the units declared in the cell_methods comment string -- only picked up by the cf-checker.
(8) IOOS checker records omission of “reference” global attribute as an error: use of this attribute is neither required nor recommended.

**Comment by jbosch-noaa** [comment] 2017-07-19 17:08
@Bobfrat  - I know a few of these issues you may be aware of.  Has it been put on a plan to update the compliance checker to fix these issues?

**Comment by daf** [comment] 2017-07-19 17:13
Hi @martinjuckes, thanks for your report.  Some early comments:

> (1) The IOOS checker records use of Conventions=CF-1.4 as an error: this was the current version of the conventions at the time the file was written, so should not be considered as an error. Rather, it is an indication that the compliance checker should check the metadata against version 1.4 of the standard.

The compliance checker was authored when 1.6 was the current offering and we didn't intend previous versions to be checked at the time.  Support can exist for them, they just haven't been built yet.

> (3) IOOS is distributed with an old version of the CF standard name table which results in spurious errors … this could probably be fixed by switching the file .. but there is no obvious warning.

The compliance checker has a mechanism for updating the standard names table at run-time and caching it locally.  See the [command line usage](https://github.com/ioos/compliance-checker#usage-command-line), specifically the `-d DOWNLOAD_STANDARD_NAMES, --download-standard-names` options.

Other issues will have to be investigated further.

**Comment by jbosch-noaa** [comment] 2017-07-19 17:23
Thanks for your quick response, @daf .  Please let me know once you have found a solution to these errors.

**Comment by martinjuckes** [comment] 2017-07-20 09:11
@daf Thanks. For the conventions flag, could you change the message issued to reflect the fact that it is an unsupported version, rather than giving the misleading message labelling it as an error in the file? I appreciate that there are limits to what can be usefully done with backward compatibility, but the information given out could be improved.

**Comment by lukecampbell** [comment] 2017-07-22 03:11
> (6) The IOOS checker has a message that “latitude variable 'rlat' should define valid units for latitude” which is incorrect: the ‘rlat’ variable has standard name grid_latitude, and the definition of grid_latitude specifies that “degree”, as used in the above file, is correct.

§4.1 of CF-1.6 States
The recommended unit of latitude is degrees_north. Also acceptable are degree_north, degree_N, degrees_N, degreeN, and degreesN.

Regardless of the standard_name table defining `degree` as the base unit, the CF-Checker regards any variable that it identifies as the latitude coordinate variable as falling under the specifications for §4.1.

If the variable is part of a rotated grid, or non-standard projection there's a way to define it, I'd have to check the spec and read the code again.

**Comment by lukecampbell** [comment] 2017-07-22 03:19
> (5) Cf-checker lists one error in the cell_methods string, IOOS has this as a priority 2 message -- which is usually associated with a warning.

The IOOS Compliance Checker's semantics for priorities are not a direct mapping with concepts of error, warning or info. We simply mean, priority 3 being the highest priority, and 1 being the lowest. There is no pass/fail with the IOOS Checker because standards are not defined clearly enough where they can be programmed in a logical and reasonable way. Because of this, we decided to use ordinals for priorities. 

When the checker identifies something that does not conform to recommendations, or requirements specified in the standard being checked, we make an effort to associate that non-conformance with a useful message and ideally guidance for how to correct, but the guidance is still a work-in-progress. 

A rule of thumb, if the CF-1.6 standards says _must_, _required_, _shall_, the conformance is generally associated with priority 3. If it's a _recommendation_, it is usually a 2. This is not a hard rule, we look at how the community has decided to implement various interpretations of the standard especially §5 and we adjusted the priorities based on that. We also take feedback and adjust the priorities based on community feedback through the github issues.

**Comment by lukecampbell** [comment] 2017-07-22 03:20
> (2) The variable “aps” is referred to in a formula_terms attribute but not defined: IOOS misses this;

That's a bug and we'll need to create a separate issue to track this.

**Comment by lukecampbell** [comment] 2017-07-22 03:21
> (8) IOOS checker records omission of “reference” global attribute as an error: use of this attribute is neither required nor recommended.

§ 1.3 of CF-1.6 states
> The general description of a file’s contents should be contained in the following attributes: title , history , institution , source , comment and references ( Section 2.6.2, "Description of file contents" ). For backwards compatibility with COARDS none of these attributes is required, but their use is recommended to provide human readable documentation of the file contents.

Therefore the attributes are recommended and part of the checker as designed.

**Comment by lukecampbell** [comment] 2017-07-22 03:35
Thank you for bringing these issues to our attention. It's really helpful to see example files like you provided and to get good feedback like this.

**Comment by martinjuckes** [comment] 2017-07-22 06:55
@lukecampbell On (6): the point is that "grid_latitude" is a different variable to "latitude", it refers to a grid with arbitrary orientation, so using degree_north is an error here. The standard name table is part of the standard, and the information it is providing is correct and consistent with the section of the standard you quote once you recognise the crucial difference between latitude and grid_latitude.

On (5) the standard is set by the community .. perhaps you are talking to a different community, in which case you might want to give it a different name. If you want to support the development of the standard it would be better to engage with it directly. There is no lack of clarity in the definition here, and if you see lck of clarity elsewhere it would be useful to have it pointed out. I agree that there are many standards that suffer from lack of clarity, but the CF standard undergoes very detailed discussion on every point. 

On (8): I don't see the phrase "recommended" in the text you quote. As I mentioned, the standard is carefully written. There is also a compliance document which you should take a look at which sets out the requirements and recommendations more clearly: http://cfconventions.org/Data/cf-documents/requirements-recommendations/requirements-recommendations-1.6.html for CF-1.6 and http://cfconventions.org/Conformance/conformance.html for CF-1.7 (draft).  You could argue for a change in the conformance document ... but it would be better to do that by submitting your ideas to the CF discussion list. 

On (2): thanks

There is a general point about consistency. As I noted above, the CF convention is actually very good in terms of precise language, but the complexity does bring problems, particulary in the fact that many of the user community do not have time get to grips with the details. I think your work would be far more useful if you used the conformance document and provided clear feedback whenever you find, as is inevitable, details which are unclear to either you or the users (perhaps one problem is that the conformance document is not very visible?). It is slow, but issues get picked up and the standard needs such contributions from the community.

**Comment by lukecampbell** [comment] 2017-07-22 14:01
> On (8): I don't see the phrase "recommended" in the text you quote. 

> The general description of a file’s contents should be contained in the following attributes: title , history , institution , source , comment and references ( Section 2.6.2, "Description of file contents" ). For backwards compatibility with COARDS none of these attributes is required, but their use is **recommended** to provide human readable documentation of the file contents.

**Comment by lukecampbell** [comment] 2017-07-22 14:02
> On (6): the point is that "grid_latitude" is a different variable to "latitude", it refers to a grid with arbitrary orientation, so using degree_north is an error here. The standard name table is part of the standard, and the information it is providing is correct and consistent with the section of the standard you quote once you recognise the crucial difference between latitude and grid_latitude.

You are correct that's a bug.

**Comment by lukecampbell** [comment] 2017-07-22 14:07
When I was working on version 3, I did engage with CF indirectly through the NOAA netCDF group. I even made corrections to the standard via pull-requests.

**Comment by lukecampbell** [comment] 2017-07-22 14:39
I'll try to take a look at these at some point. In the mean time, I'd like to break them up into individual issues and continue conversations about them separately.

**Comment by lukecampbell** [comment] 2017-07-27 16:01
@Bobfrat, I recommend we close this issue in favor of the issues we opened. That way we don't introduce cross-talk on different issues.

**Comment by Bobfrat** [comment] 2017-07-27 16:04
Closing in favor of the individual issues created

**Closed by Bobfrat** 2017-07-27 16:04 UTC

**Comment by benjwadams** [comment] 2017-08-08 22:29
@martinjuckes, I realize this issue is closed, but I am not able to access the links to the files you mentioned.  Being able to access these files would expedite things a great deal.  Is it possible to convert the data over to CDL format and upload them to GitHub Gists?

**Comment by martinjuckes** [comment] 2017-09-13 12:55
Sorry, the wiki formatting of the links was incorrect ... they should work now (giving you access to the NetCDF files)

**Comment by benjwadams** [comment] 2017-09-19 17:01
@martinjuckes, thanks, they are working again.
