### ISSUE TITLE
Checker for zarr datasets?

### ISSUE THREAD

**Issue by mwengren** [ioos/compliance-checker#672] opened 2019-08-26 21:37 UTC
How challenging would it be to add the ability for CC to validate compliance of zarr datasets (local or remote/HTTP) with some of the existing checks?   

Dependency would be xarray to read zarr files (and maybe some others, not sure). 

* We could check attribution for ACDD compliance of attributes
* Check for relevant aspects of CF-compliance of zarr datasets
* Others?

**Comment by benjwadams** [comment] 2021-07-12 15:10
Recent versions of NetCDF-C have the ability to use Zarr as the storage backend, so this may now be doable with minimal effort.

**Comment by benjwadams** [comment] 2021-07-12 21:36
This might actually just work if we have a Zarr NetCDF file we can point to on some accessible remote location.

**Comment by ocefpaf** [comment] 2021-07-13 18:05
@benjwadams take a look [at this gist](https://gist.github.com/ocefpaf/4a078b19db4fd5507d2d21691abaa689). The CDL I used there is from complance-checker's test suit BTW.

**Comment by openSourcerer9000** [comment] 2021-09-16 15:21
@ocefpaf Your notebook was very helpful, but I am hitting a wall when trying to read or ncdump the example dataset on S3. This is the complaint it gives me:

`OSError: [Errno -128] NetCDF: Attempt to use feature that was not turned on when netCDF was built.`

It seems netCDF-C needs to be built with one of these flags turned on:

Automake
`--enable-nczarr-s3 -- Enable NCZarr S3 support.`
CMake
`-DENABLENCZARRS3=off -- equivalent to the Automake --enable-nczarr-s3 option.`

in order for it to build NetCDF with the AWS C++ SDK, at least that’s what I understand [from this](https://www.unidata.ucar.edu/blogs/developer/entry/overview-of-zarr-support-in#:~:text=different%20from%20zlib.-,Amazon%20S3%20Storage,-The%20Amazon%20AWS). I looked at the conda-forge feedstocks for compliance-checker and netcdf4 and didn't notice anything about custom flags. It seems like in order to support S3 datasets, it would need to be specified as the default when the python lib installs. 

I'm not sure we really want AWS SDK for C++ as a dependency for compliance checker. Maybe we just make the user download their dataset onto local before running compliance-checker on a Zarr? Any strong opinions on this? Do we think there is a reasonable way to maintain AWS SDK as an optional dependency?

**Comment by benjwadams** [comment] 2021-09-16 15:27
> in order for it to build NetCDF with the AWS C++ SDK, at least that’s what I understand from this. I looked at the conda-forge feedstocks for compliance-checker and netcdf4 and didn't notice anything about custom flags. It seems like in order to support S3 datasets, it would need to be specified as the default when the python lib installs.

Once we have a working S3 example, we can note in the README that S3-Zarr support requires NetCDF to be compiled with the appropriate libraries.

**Comment by openSourcerer9000** [comment] 2021-09-16 15:43
I'm C-illiterate, and haven't found documentation on how to rebuild a C lib inside a conda env. That unidata explainer mentions "Refer to the installation manual for details", but I wasn't able to find that manual. I think we'll want to have solid documentation on how to set up S3-nczarr support if users need to recompile a C lib 3 levels down from compliance-checker in order to pass the capability through to compliance-checker's API. 

I'm wondering if we could fork the conda-forge feedstock with the appropriate build options enabled, so a user interested in testing S3 datasets could simply `$ conda create -n myenv -c conda-forge python compliance-checker-with-s3` to get the env set up properly.

**Comment by ocefpaf** [comment] 2021-09-16 16:26
Please see https://github.com/conda-forge/libnetcdf-feedstock/pull/125 for the issues with S3. If you can help upstream, either conda-forge to reproduce the same conditions netcdf-c tests use or make netcdf-c S3 support more robust, that will be very welcomed by the community. At the moment, S3 is pretty much broken/beta testing IMO due to the difficulties in reproducing the exact same build conditions from upstream.

**Comment by openSourcerer9000** [comment] 2021-09-16 16:49
Personally I'm out of my element working with dependencies upstream of Python. One hack I can imagine is using a python lib like d6tpipe to download the dataset to a local Zarr first, and then running the checker on it. The downside is that this likely adds processing time if the test data is big. The advantage I see for compliance checker is that a user can easily manage this optional dependency from the same package manager they got checker from, but it won't necessarily benefit upstream tools in the ecosystem.

**Comment by benjwadams** [comment] 2024-05-30 15:31
Closing due to changes in #1071 implemented in code sprint.

**Closed as completed by benjwadams** 2024-05-30 15:31 UTC
