### ISSUE TITLE
File Independent Scoring Concept

### ISSUE THREAD

**Issue by mbiddle-bcodmo** [ioos/compliance-checker#109] opened 2015-05-05 12:52 UTC
Hi all,

This might not be worth talking about, but I wanted to at least get it out in the open if it's something other people could find useful.

One of my thoughts is to use this compliance checker for different groups of data providers to test if their netCDF files are correctly formatted for transmission to the archive. Reviewing my understanding of how the scoring system works, the current incarnation has a varying amount of total available points depending on the files and tests. I understand that comparing between tests should yield differing scores, however, providing some consistency between varying files (using the same test) would be useful. 

It would be beneficial, from the NCEI perspective, if there was some consistent number to represent the score the file receives for each specific test. This would facilitate the use of the compliance checker across a breadth of files and provide a consistent evaluation for all files. 

My thought is that NCEI could say something along the lines of 'Your files should have a compliance checker score larger than X.' Although, now that I think about it, maybe evaluating the score as a percentage would suffice for these needs.

**Comment by lukecampbell** [comment] 2015-07-14 19:52
Hey Matt, we're in the process of reevaluating the entire scoring process for compliance checker as it is. 
We're struggling with conflicting desires:

1. Users want a simple "pass/fail" answer to the question "is this dataset good enough".
   - The problem is, that answer is not an easy one to come up with.
2. Users want guidance for how to fix their datasets if it's not good enough.
3. There are varying degrees of compliance and for documents like CF, compliance is sometimes up to interpretation of the document, and therefore debatable.

**Comment by mbiddle-nodc** [comment] 2015-07-16 12:11
I understand the difficulty with trying to implement a scoring concept that covers both the simple "pass/fail" concept but also provides enough details to fix the datasets. As far as the interpretation of the guidance documents, as long as you describe how the documentation was interpreted, that's the best that can be done. 

Another resource that I was just made aware of, apparently JPL has developed an online compliance checker for CF, ACDD, and GDS2 (very specific guidance for GHRSST data sets). http://podaac-uat.jpl.nasa.gov/mcc/.

**Comment by daf** [comment] 2015-07-16 13:07
Nice, they made it available!  They had an intern develop a GUI on top of this same compliance-checker  in Summer 2014.  At the time, they hadn't planned on releasing anything though.

**Comment by kknee** [comment] 2015-07-16 13:14
+1 on being happy to see the JPL version released!

**Comment by abirger** [comment] 2015-07-16 15:49
Wow, that GUI looks nice! It is what I had in mind in the Trade Study recommendations. 
I like the report of the exact data model used for the file encoding. I also like the way ACDD attributes are categorized: strictly following the convention (highly recommended, recommended, suggested) rather then using  High, Medium, and Low priorities. The latter, however, is not at all critical, and may even be an advantage if we allow IOOS Compliance Checker to configure different priorities for the customized tests.
On the other hand, I don't like too much the report format. It seems excessively verbose and cluttered - especially the PDF report where you get all bullets expanded. I kind of like it better when the scoring is separated from the reasoning - like the IOOS Checker does it.

**Comment by mhidas** [comment] 2015-08-17 08:02
Our use case here at IMOS is similar to what @mbiddle-nodc describes (if I'm interpreting it correctly). To us, the only useful outputs are

 1. A pass/fail result so we can automatically decide whether the file is ready to publish.
 2. Feedback to help the data provider fix the file.

(The "passed X tests out of Y" score doesn't really help, because e.g. if a file passes every check 
except is doesn't have a `Conventions` global attribute, we still won't publish it.)

The checker already provides these outputs, as 1) a single return value on exit, and 2) reasoning messages. The only thing I think needs improvement in some cases is the content of the reasoning messages.

Even @lukecampbell's third point is addressed to an extent, by having three priority levels, and a command-line switch (`--criteria={lenient,normal,strict}`) to control which priority levels affect the final pass/fail result.

Unfortunately I don't seem to have access to the JPL site mentioned above, but the HTTP output option added recently (#140) looks nice.

**Comment by lukecampbell** [comment] 2015-09-14 15:18
I would also like to point out that I've started development on a compliance checker web version.
https://github.com/ioos/compliance-checker-web/

**Comment by DanielJMaher** [comment] 2016-02-08 19:39
To fire this thread back up, @lukecampbell @mbiddle-nodc , have we determined a way to say "Yes this dataset is good enough"?

I would imagine that passing every high priority is a must, but from there I see 2 schools of thought: 
1) Every High Priority and some minimum percentage of Medium Priority (75%?)
2)  Only High Priority matters

**Comment by kknee** [comment] 2016-02-08 21:48
@DanielJMaher we worked this out with @mbiddle-nodc on a recent call about the NCEI plugin.  I'll put the details in that repo.

**Comment by Bobfrat** [comment] 2018-03-05 18:43
this will be addressed as part of the scoring overhaul:

https://github.com/ioos/compliance-checker/issues/37

**Comment by benjwadams** [comment] 2018-03-07 17:39
Yeah, there's a lot of duplicate discussion between here and #37.  I am going to close this and further discussion can be moved there.

**Closed by benjwadams** 2018-03-07 17:39 UTC
