### ISSUE TITLE
Due Date for "Version 2.2: ACDD 1.3 and other IOOS vocabulary modifications"

### ISSUE THREAD

**Issue by jbosch-noaa** [ioos/compliance-checker#244] opened 2016-04-06 14:35 UTC
Where are we with this milestone?  Are their any significant hangups or time constraints?  I would like for us to formally put a due date on here.

**Comment by kknee** [comment] 2016-04-11 12:04
@jbosch-noaa we'll get a due date on here this week.

**Comment by benjwadams** [comment] 2016-04-26 17:03
By tomorrow, 2016-04-27, I believe.

**Comment by kknee** [comment] 2016-04-26 17:57
Edit - @benjwadams is waiting on some pull requests to be reviewed hopefully sometime this week by @lukecampbell

**Comment by dpsnowden** [comment] 2016-05-02 15:22
poke

**Comment by kknee** [comment] 2016-05-02 15:25
@dpsnowden all pull requests have been merged.  @lukecampbell will package the release as soon as  today's EDS Viewer release is finalized.

**Comment by jbosch-noaa** [comment] 2016-05-31 13:29
@kknee where are we on this? Can I check it off the list yet?

**Comment by kknee** [comment] 2016-05-31 17:11
Yes,  we did that release a couple of weeks ago.

Sent from my iPhone

On May 31, 2016, at 9:29 AM, Jennifer Bosch <notifications@github.com<mailto:notifications@github.com>> wrote:


@kknee<https://github.com/kknee> where are we on this? Can I check it off the list yet?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/ioos/compliance-checker/issues/244#issuecomment-222688138>, or mute the thread<https://github.com/notifications/unsubscribe/AAMBBFJibiV_bwfoEnAU7SUTH3KZNOIGks5qHDelgaJpZM4IBJe0>.

This e-mail message and any attached file is the property of the sender and is sent in confidence to the addressee only.
Internet communications are not secure and RPS is not responsible for their abuse by third parties, any alteration or corruption in transmission or for any loss or damage caused by a virus or by other means.
 
Any advice contained in this e-mail is for information purposes only.

RPS Group Plc, company number: 208 7786 (England). Registered office: 20 Western Avenue Milton Park Abingdon Oxfordshire OX14 4SH.
RPS Group Plc web link: <http://www.rpsgroup.com>

**Closed** 2016-06-06 16:06 UTC
