### ISSUE TITLE
WKT possible bad value

### ISSUE THREAD

**Issue by mstoessel** [ioos/compliance-checker#654] opened 2019-05-23 14:40 UTC
" Could not parse WKT, possible bad value for WKT"
Could you please be more specific what this means.
Thank you

**Comment by Bobfrat** [comment] 2019-05-23 19:30
@mstoessel Thanks for using the compliance checker. Can you provide some more info about how you got this message? For example which attribute/variable, which test were run, and were you using the web version or command line? A url to the file or .cdl is usually helpful when posting issues here as well.

My best guess is that this error came from the geospatial_bounds attribute check in the ACDD 1.3 test. Here's the link to ACDD 1.3 Convention:

http://wiki.esipfed.org/index.php/Attribute_Convention_for_Data_Discovery_1-3#geospatial_bounds

The message indicates that the value is not a valid OGC WKT string.

Is the confusion on what WKT means? Or do you think you provided a valid WKT and want the message to be more specific on how it's not valid?

**Comment by mstoessel** [comment] 2019-05-23 22:16
Hi Bob

Well I thought I had provided a valid OGC WKT string.  I used the example provided for the " geospatial_bounds "  with different coordinates since I needed to specify spacial extent. 
This message has come up several times. You were right it had to do with  " geospatial_bounds ". I finally found the culprit, a spelling error. 
It would be nice if it the possible culprit could be narrow a bit. I found the mistake because you wrote that it might be the " geospatial_bounds ", so I concentrated on that.
Before I was searching the global attributes list on was not sure what to look for.
I'm using the command line version, IOOS compliance checker version 4.2.2 and run the default configuration.
I create netCDF files that go on an ERDDAP server so I use the compliance-checker quit frequently.

Thank you for your fast response
Marion

-------------------------------------------------------------------------------------------------
Marion Stoessel
Senior Research Associate
Department of Oceanography                     Tel.:  ++1 979 845-7662
Texas A&M University                                Fax.:++1 979 847-8879
College Station. TX 77843-3146                  e-mail:mstoessel@ocean.tamu.edu
Join GCOOS on Facebook: https://www.facebook.com/GCOOS

------------------------------------------------------------------------------------------------
________________________________________

**Comment by Bobfrat** [comment] 2019-05-24 00:17
Glad you found the culprit and really happy to hear that you're using the compliance checker in your data workflow. I'll keep this ticket open and see if we can improve the messaging for this error.

**Comment by fgayanilo** [comment] 2019-05-24 14:06
I agree that a bit more details on the error will help, like printing the value itself that caused the error.

**Comment by mstoessel** [comment] 2019-05-24 19:50
Hi Nonong

I haven't seen Laura. I asked the students in the in the office was told that they haven't seen her since Monday.
Just wanted to let you know that the portable  hard drive has not been purchased jet. 
I had send her two e-mails one to purchase the hard drives with cases and an other to send one hard drive to Corpus Christi and one to CS.

Have a nice Memorial Day week end
Marion 
-------------------------------------------------------------------------------------------------
Marion Stoessel
Senior Research Associate
Department of Oceanography                     Tel.:  ++1 979 845-7662
Texas A&M University                                Fax.:++1 979 847-8879
College Station. TX 77843-3146                  e-mail:mstoessel@ocean.tamu.edu
Join GCOOS on Facebook: https://www.facebook.com/GCOOS

------------------------------------------------------------------------------------------------
________________________________________

**Comment by benjwadams** [comment] 2019-05-28 18:09
Hi, I assume it was an accident, but please don't use this repo issues for personal communications.  If you could send a CDL or the netCDF, it'd be more helpful to us to reproduce this issue.

**Comment by benjwadams** [comment] 2019-07-02 21:16
Closing until a CDL or NetCDF file demonstrating that the aforementioned error message is unclear in the context of the error report.

**Comment by benjwadams** [comment] 2019-07-03 20:50
#660 now displays the WKT value that caused the failure, and notes that the `geospatial_bounds` attribute is the global attribute in question.  Re-closing due to fix.

**Closed by benjwadams** 2019-07-03 20:50 UTC
